### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by JihedC**
Hi guys,
The develop branch is working, I commented some results of the rule_all. We can work on fixing the rules that are not working on individual branch.

### CODE REVIEW

**Comment by JihedC** [comment]
Tijs should try the pipeline for the clustering and the plotting with a proper count file, if it works we can just uncomment the rule all that I have for now commented

**Comment by mgalland** [comment]
@tijsbliek right. But somehow, even with the "use conda" it actually does not use it on my Mac OS X. Should we include it in the `global_env.yaml` file and delete the `conda` keywords in the rules where it downloads the genomes + transcriptome?

**Comment by mgalland** [comment]
Works on the genseq system (`Linux genseq-cn02.science.uva.nl 2.6.32-754.10.1.el6.x86_64 #1 SMP Tue Jan 15 17:07:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`).

On my Mac OS X (`Darwin u031224.1x.uva.nl 17.7.0 Darwin Kernel Version 17.7.0: Wed Apr 24 21:17:24 PDT 2019; root:xnu-4570.71.45~1/RELEASE_X86_64 x86_64`), I have an issue at the `rule create_counts_table` level where it states:
```
/bin/bash: activate: No such file or directory
/bin/bash: featureCounts: command not found
``` 
I think these kind of issues should be solved by using containers. I will make a `docker` branch and a related pull request soon.

So for now, good for me!

**Comment by JihedC** [comment]
I have tried the pipeline with a counts.txt file that Tijs provided me on Saturday and it works well, I think we can merge the branch to master. 
May be we can add this count file in a folder for "test" and document it.

**Comment by JihedC** [comment]
If everyone is okay, I will merge the branches

**Comment by tijsbliek** [comment]
I am ok. go for it.

**Comment by mgalland** [comment]
Go 🐎 go 🏇 go!

**Pull request merged**
